// Code generated by "stringer -type EncodingType"; DO NOT EDIT

package cpio

import "fmt"

const _EncodingType_name = "EncodingTypeASCIISUSv2EncodingTypeASCIISVR4EncodingTypeASCIISVR4CRCEncodingTypeBinary"

var _EncodingType_index = [...]uint8{0, 22, 43, 67, 85}

func (i EncodingType) String() string {
	if i < 0 || i >= EncodingType(len(_EncodingType_index)-1) {
		return fmt.Sprintf("EncodingType(%d)", i)
	}
	return _EncodingType_name[_EncodingType_index[i]:_EncodingType_index[i+1]]
}
